version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:${PORT:-8000}
    volumes:
      - .:/src
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    environment:
      - PORT=${PORT:-8000}