version: '3'
services:
  web:
    build: .
    env_file:
      - .env
    volumes:
      - ./public:/public
      - ./db.sqlite3:/db.sqlite
      - ./members.sqlite3:/members.sqlite3
    ports:
     - "${PORT}:5000"
    restart: always